version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
  server:
    build: .
    restart: always
    depends_on:
      - mongo
    ports:
      - "3000:3000"
